name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.15.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      
    - name: Install wasm
      run: rustup target add wasm32-unknown-unknown
      
    - name: Install node dependencies
      working-directory: node_dependencies
      run: yarn
    
    - name: Build
      run: ./trunk build
      
    - name: Publish to github pages
      shell: bash
      run: |
        echo "creating tmp dir"
        TEMP_DIR=$(mktemp -d)
        echo "tmp dir is $TEMP_DIR"
        echo "tmp dir content 1 $(ls $TEMP_DIR)"
        mv "./dist" "$TEMP_DIR"
        echo "tmp dir content 2 $(ls $TEMP_DIR)"
        echo "tmp dir content 3 $(ls $TEMP_DIR/dist)"
        git switch -c "gh-pages" || git switch "gh-pages"
        echo "tmp dir content 4 $(ls $TEMP_DIR)"
        rm -rf *
        echo "tmp dir content 5 $(ls $TEMP_DIR/dist)"
        mv "$TEMP_DIR/dist/*" .
        echo "tmp dir content 6 $(ls $TEMP_DIR)"
        git push
